// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'app_home',
    uri: Uri.parse('app_home'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(key: 'login', uri: Uri.parse('login'), routeBuilder: b1Builder),
  RouteEntity(
    key: 'profile',
    uri: Uri.parse('profile'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'review/create_review',
    uri: Uri.parse('review/create_review'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'review/edit_review',
    uri: Uri.parse('review/edit_review'),
    routeBuilder: b4Builder,
  ),
];

const routePaths = (
  path: '/',
  appHome: '/app_home',
  login: '/login',
  profile: '/profile',
  review: (
    path: '/review',
    createReview: '/review/create_review',
    editReview: '/review/edit_review',
  ),
);
