// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'app_home',
    uri: Uri.parse('app_home'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: 'auth/login',
    uri: Uri.parse('auth/login'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'auth/register',
    uri: Uri.parse('auth/register'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'profile',
    uri: Uri.parse('profile'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'review/create_review',
    uri: Uri.parse('review/create_review'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'review/edit_review',
    uri: Uri.parse('review/edit_review'),
    routeBuilder: b5Builder,
  ),
];

const routePaths = (
  path: '/',
  appHome: '/app_home',
  auth: (path: '/auth', login: '/auth/login', register: '/auth/register'),
  profile: '/profile',
  review: (
    path: '/review',
    createReview: '/review/create_review',
    editReview: '/review/edit_review',
  ),
);
